### ISSUE TITLE
Formatting of the Confirmation Page/Broken Link

### ISSUE THREAD

**Issue by AveryFerrante** [Gooey-Dee-Bee/Ripple-app#30]
Not sure if someone from GUI wants to/has time to look into this, but right now when a user clicks the link in their email to activate their account, they are brought to a really bland confirmation page (see picture). I just wrote super basic HTML. Look in the accountConfirm.php file if you want to try to make it look a little better. Also, clicking the 'take me to ripple' link doesn't work.
![screenshot from 2015-04-30 14 11 34](https://cloud.githubusercontent.com/assets/5977374/7420525/daee7b16-ef42-11e4-9a10-370fdacc8717.png)

**Comment by williamoconnor** [comment]
Is this supposed to be in the Ripple repo, as opposed to Ripple-App?
